### ISSUE TITLE
1.3.5同步错误，无法获取信息

### ISSUE THREAD

**Issue by mjsoftking** [chengzhongxue/plugin-friends#2]
降级1.3.4可以同步

``` java

2024-10-05T08:28:41.091+08:00 ERROR 7 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in la.moony.friends.reconciler.SyncFriendPostReconciler-worker-1 aborted with an error, re-enqueuing...

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Unknown Source) ~[na:na]
	at la.moony.friends.reconciler.SyncFriendPostReconciler.tryToSynchronizeFriendPost(SyncFriendPostReconciler.java:95) ~[na:na]
	at la.moony.friends.reconciler.SyncFriendPostReconciler.lambda$reconcile$0(SyncFriendPostReconciler.java:76) ~[na:na]
	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
	at la.moony.friends.reconciler.SyncFriendPostReconciler.reconcile(SyncFriendPostReconciler.java:64) ~[na:na]
	at la.moony.friends.reconciler.SyncFriendPostReconciler.reconcile(SyncFriendPostReconciler.java:42) ~[na:na]
	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.19.3.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by mjsoftking** [comment]
完全卸载，重新安装1.3.5可以获取新数据了，在监控看看定时更新是否正常
1.3.4升级1.3.5的不行，完全不更新数据
